# Generated by Django 2.2.5 on 2019-09-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190604_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default="{% static 'image/bye.jpg' %}", upload_to='img/', verbose_name='Image of User'),
        ),
    ]
